### ISSUE TITLE
Errors during test

### ISSUE THREAD

**Issue by DaniloDel** [gplepage/vegas#20]
I ran the tests, however I received some errors with mismatching types. Could you please help? The full output is below. 

c:\vegas-master>py -m unittest discover
...................................EE.EE...........
======================================================================
ERROR: test_ravgarray_unwgtd (tests.test_vegas.TestRAvg)
unweighted RAvgArray
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\vegas-master\tests\test_vegas.py", line 300, in test_ravgarray_unwgtd
    for ri in r:
  File "_utilities.pyx", line 2362, in raniter
  File "_utilities.pyx", line 2933, in gvar._utilities.regulate
  File "_utilities.pyx", line 3217, in gvar._utilities.svd
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'

======================================================================
ERROR: test_ravgarray_wgtd (tests.test_vegas.TestRAvg)
weighted RAvgArray
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\vegas-master\tests\test_vegas.py", line 281, in test_ravgarray_wgtd
    for rb, rs in zip(rbig, rsmall):
  File "_utilities.pyx", line 2362, in raniter
  File "_utilities.pyx", line 2933, in gvar._utilities.regulate
  File "_utilities.pyx", line 3217, in gvar._utilities.svd
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'

======================================================================
ERROR: test_ravgdict_unwgtd (tests.test_vegas.TestRAvg)
unweighted RAvgDict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\vegas-master\tests\test_vegas.py", line 372, in test_ravgdict_unwgtd
    for ri in r_a:
  File "_utilities.pyx", line 2362, in raniter
  File "_utilities.pyx", line 2933, in gvar._utilities.regulate
  File "_utilities.pyx", line 3217, in gvar._utilities.svd
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'

======================================================================
ERROR: test_ravgdict_wgtd (tests.test_vegas.TestRAvg)
weighted RAvgDict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\vegas-master\tests\test_vegas.py", line 407, in test_ravgdict_wgtd
    for rb, rw in zip(rbig_a, rsmall_a):
  File "_utilities.pyx", line 2362, in raniter
  File "_utilities.pyx", line 2933, in gvar._utilities.regulate
  File "_utilities.pyx", line 3217, in gvar._utilities.svd
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'

----------------------------------------------------------------------
Ran 51 tests in 2.448s

FAILED (errors=4)

**Comment by gplepage** [comment]
Thanks for pointing out the problem. I won’t be able to fix it until next week (because I won’t have access to adequate internet until then).

**Comment by gplepage** [comment]
This appears to be a problem in the ``gvar`` module, which is used by ``vegas``. Try replacing your ``gvar`` with the latest version (11.9.4), which I just posted.

**Comment by DaniloDel** [comment]
Thank you very much, it worked perfectly. Best regards!
